version: "3.3"
#----------------------------------------------------------
# definicion de la red y rango de ips
#
# 172.27.3 ip net
#----------------------------------------------------------
networks:
  curso-backend-jwt-typescript-network:
    ipam:
      config:
        - subnet: 172.27.3.0/24
services:
  curso-backend-jwt-typescript-mongodb:
    image: mongo
    container_name: "curso-backend-jwt-typescript.mongodb"
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=curso-backend-jwt-typescript
    volumes:
      - ../mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    hostname: curso-backend-jwt-typescript.mongodb
    networks:
      curso-backend-jwt-typescript-network:
        ipv4_address: 172.27.3.11
    command: mongod  --quiet --logpath /dev/null  --bind_ip 127.0.0.1,172.27.3.11

  curso-backend-jwt-typescript-mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=172.27.3.11
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=curso-backend-jwt-typescript
      - ME_CONFIG_MONGODB_AUTH_USERNAME=
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - curso-backend-jwt-typescript-mongodb
    ports:
      - 8888:8081
    restart: unless-stopped
    extra_hosts:
      - "mongodb:172.27.3.11"
    networks:
      curso-backend-jwt-typescript-network:
        ipv4_address: 172.27.3.12

  curso-backend-jwt-typescript.api:
    user: "1000:1000"
    build: api
    container_name: "curso-backend-jwt-typescript.api"
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ../api/:/var/www/vhosts/curso-backend-jwt-typescript/
    hostname: curso-backend-jwt-typescript.api
    extra_hosts:
      - "mongodb:172.27.3.11"
    networks:
      curso-backend-jwt-typescript-network:
        ipv4_address: 172.27.3.10
    links:
      - curso-backend-jwt-typescript-mongodb